### ISSUE TITLE
BUG: Collapsed toolbar does not change when clicking on different WB

### ISSUE THREAD

**Issue by akamensky** [HakanSeven12/Modern-UI#7] opened 2020-10-17 15:44 UTC
# System info:

```
OS: macOS 10.15
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22670 (Git)
Build type: Release
Branch: master
Hash: 12155f4aab09047c5697db0c1b3cf93b02edda03
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: C/Default (C)
```

# Steps

1. Select a WB
2. Collapse WB toolbar (minimize)
3. Click on another WB "tab" while still minimized

# Expected

The pop-up will be for the WB that was clicked.

# Actual

The pop-up is for the WB that was active when toolbar was collapsed.

# Details

I love how it frees up space when I can collapse the toolbar, but it is not usable in current form because to switch between toolbars or to even get to "menu" one (to open/save files etc) I have to expand the toolbar.

![https://media.giphy.com/media/v6F8vGw4IaHTcrV4ZQ/giphy.gif](https://media.giphy.com/media/v6F8vGw4IaHTcrV4ZQ/giphy.gif)

**Comment by HakanSeven12** [comment] 2021-01-22 06:37
I can't reproduce this issue maybe it was fixed. Can you try again? I'm closing this issue for now. if you still have same bug, report me.

**Closed as completed by HakanSeven12** 2021-01-22 06:37 UTC
